on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Perform the jest test
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run jest
        run: npm run test
